name: frontend/renovate
on:
  workflow_dispatch:
    inputs:
      prCount:
        description: 作成するPRの数
        required: true
        type: number
        default: 10
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Count Renovate PR Count
        run: |
          RENOVATE_PR_COUNT=$(gh api graphql -F "query={
            repository(
              owner:\"shgtkshruch\",
              name:\"monorepo-renovate-sample\"
            ) {
              pullRequests(first: 100, states: OPEN) {
                totalCount
                nodes {
                  headRefName
                }
              }
            }
          }" --jq \
           '.data.repository.pullRequests.nodes | [.[] | select(.headRefName | contains("renovate")) ] | length')

           echo $RENOVATE_PR_COUNT

           echo "RENOVATE_PR_CONCURRENT_LIMIT=$(( ${{ inputs.prCount }}+$RENOVATE_PR_COUNT ))" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v34.102.0
        with:
          configurationFile: frontend/renovate.js
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_PR_CONCURRENT_LIMIT: ${{ env.RENOVATE_PR_CONCURRENT_LIMIT }}
